[versions]
agp = "8.6.0-alpha07"
bugsnagAndroid = "6.2.0"
flexbox = "3.0.0"
kotlinxCoroutinesAndroid = "1.8.0"
okhttp = "4.12.0"
robolectric = "4.11.1"
round = "1.1.2"
toaster = "12.6"
xmltojson = "1.5.3"
xposed = "82"
gson = "2.10.1"
htmlKtx = "1.1.2"
kotlin = "1.9.21"
core-ktx = "1.12.0"
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
appcompat = "1.6.1"
themeEngine = "-SNAPSHOT"
ultimateBarX = "dev-SNAPSHOT"
navigationFragment = "2.7.7"
browser = "1.8.0"
activity = "1.8.2"
constraintlayout = "2.1.4"
dexlib2 = "2.5.2"
[libraries]
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationFragment" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationFragment" }
bugsnag-android = { module = "com.bugsnag:bugsnag-android", version.ref = "bugsnagAndroid" }
flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "flexbox" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
round = { module = "io.github.xiaofeidev:round", version.ref = "round" }
toaster = { module = "com.github.getActivity:Toaster", version.ref = "toaster" }
xmltojson = { module = "com.github.smart-fun:XmlToJson", version.ref = "xmltojson" }
xposed = { module = "de.robv.android.xposed:api", version.ref = "xposed" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
html-ktx = { module = "dev.rikka.rikkax.html:html-ktx", version.ref = "htmlKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version = "1.12.0-alpha03" }
themeEngine = { module = "com.github.AnkioTomas:ThemeEngine", version.ref = "themeEngine" }
ultimateBarX = { module = "com.github.zackratos:UltimateBarX", version.ref = "ultimateBarX" }
androidx-browser = { group = "androidx.browser", name = "browser", version.ref = "browser" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
dexlib2 = { module = "org.smali:dexlib2", version.ref = "dexlib2" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }


