name: Beta Build

on:
  # 手动触发
  workflow_dispatch:


permissions: write-all

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: set beijing timezone
        uses: szenius/set-timezone@v1.2 # 设置虚拟环境的时区，可更改时区
        with:
          timezoneLinux: "Asia/Shanghai"
      - name: 下载代码
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 设置Java编译环境
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
      - name: 编译安卓
        run: |
          pip install requests  && python .github/workflows/main.py
        env:
          GITHUB_WORKSPACE: ${{ env.GITHUB_WORKSPACE }}
          ALIST_TOKEN: ${{ secrets.ALIST_TOKEN }}
          FORUMS_API_KEY: ${{ secrets.FORUMS_API_KEY }}
          BUILD_TOOLS_VERSION: 34.0.0
          SIGN_ALIAS: ${{ secrets.SIGN_ALIAS }}
          SIGN_PASSWORD: ${{ secrets.SIGN_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHANNEL: Beta





